### ISSUE TITLE
Erroneous double-update when restarting the update agent

### ISSUE THREAD

**Issue by martinzmw** [Azure/iot-hub-device-update#124]
This is not the same as issue #114 .

### Scenario

The update agent on my device does not run the wohle time. Instead the agent is started and stopped using a time schedule.

Updates might be deployed using the Device Update for IoT Hub cloud service while the device-update agent is stopped, i.e., device is offline.

### Observed Error

Steps to reproduce:

1. Register and connect device with IoT Hub
2. Configure the update agent on the device and start it.
3. Stop the agent on the device.
4. Import update in Device Update for IoT Hub and deploy it to the default update group for the new device. You may also use an update group.
5. After some minutes the desired update is written to the device twin. Check if update is announced in the device twin before proceeding.
6. Start the agent on the device again.

Now the update is installed twice, because the update agent checks at two points in time for new updates:
1. directly after startup ("Perform startup tasks")
2. just after updating the properties, e.g., manufacturer and model information in the device twin.

See also: [update-agent-1.log](https://github.com/Azure/iot-hub-device-update/files/8048032/update-agent-1.log)

I'm currently only using the setup from the tutorial https://docs.microsoft.com/en-us/azure/iot-hub-device-update/device-update-ubuntu-agent .

Yes, I just use an apt-manifest to install aziot-identity-service and aziot-edge in the current version on my Ubuntu. But, that is enough to check if the update-installation was triggered.

**I expect, that in a real setup, the doubled install will introduce serious problems especially with image-based updates instead of apt.**

**Comment by martinzmw** [comment]
It seems that the doubled update is not just an issue when the agent is restarted. The following log was created while the agent was still running and a new update was deployed: [update-agent-2.log](https://github.com/Azure/iot-hub-device-update/files/8124342/update-agent-2.log)

As you can see, there a two concurrent threads which process the same update in parallel.

**Comment by jw-msft** [comment]
there was a bug in the retry/cancellation logic that has been fixed and should be available in a future minor release.

**Comment by jw-msft** [comment]
@martinzmw This should be fixed by [this commit](https://github.com/Azure/iot-hub-device-update/commit/8a13a99edf5d4ccaa1615d0b2839ce3141275f0f) from the [hotfix/0.8.1 branch](https://github.com/Azure/iot-hub-device-update/commits/hotfix/0.8.1) that is being tested.
Feel free to try out that branch and see if it fixes the issue.

**Comment by martinzmw** [comment]
Hi @jw-msft ,

thanks for the update. But unfortunately, the bug is still there :( 

I have tried it with the recent commit 85df567 on branch [hotfix/0.8.1 branch](https://github.com/Azure/iot-hub-device-update/commits/hotfix/0.8.1)

Here is the log: [update-agent-3.log](https://github.com/Azure/iot-hub-device-update/files/8561531/update-agent-3.log)

I suspect the problem is that the variable `LastCompletedWorkflowId` is just set to late. In my setup the update workflow is erroneously executed twice **almost in parallel**, not one by one.

**Comment by jw-msft** [comment]
ok, thanks for trying it out. I'm looking into it.

**Comment by jw-msft** [comment]
I've confirmed this is a bug. concurrency was handled before in the workflow steps state machine when there was no concept of multiple steps, but when stepshandler was added the lock wasn't moved from within individual steps of a handler out to the top-level steps handling.

**Comment by martinzmw** [comment]
Unfortunately, I can't publish the Dockerfile. It has restricted access. But, I can provide the twin. I have only shortened the download URL. 

Steps to reproduce and the associated output:
1. Register new device in IoT-Hub: [01-initial-twin.json.txt](https://github.com/Azure/iot-hub-device-update/files/8727907/01-initial-twin.json.txt)
2. Run ADU agent an this device: [02-initial-agent-run.log](https://github.com/Azure/iot-hub-device-update/files/8727913/02-initial-agent-run.log)
3. Stop ADU agent by pressing CTRL+C -> resulting twin: [03-twin-after-initial-run.json.txt](https://github.com/Azure/iot-hub-device-update/files/8727923/03-twin-after-initial-run.json.txt)
4. Set ADUGroup tag in device twin: [04-setting-ADUGroup.json.txt](https://github.com/Azure/iot-hub-device-update/files/8727933/04-setting-ADUGroup.json.txt)
5. Create user-defined group (according to ADUGroup tag) and deployment for it. Wait until deployment is written to device twin: [05-update-written-to-twin.json.txt](https://github.com/Azure/iot-hub-device-update/files/8727944/05-update-written-to-twin.json.txt)
6. Run agent again: [06-agent-run-with-update.log](https://github.com/Azure/iot-hub-device-update/files/8727955/06-agent-run-with-update.log) --> This is a real use-case! The device will be only online periodically and thus typically after the update is written to the device twin.
7. Final twin: [07-final-twin.json.txt](https://github.com/Azure/iot-hub-device-update/files/8727960/07-final-twin.json.txt)

After checking the log again from step 6 (as well as update-agent-3.log provided in an earlier comment), I have seen that only the download is actually executed twice. But this is also a problem because the update file has 480 MB in the real use-case. Here it is just an APT manifest for demonstration purpose.

The install step seems to be only executed once, but on the other hand there is an "Apply succeeded" before "Action 'Install' complete". Excerpt from step 6:
```
2022-05-19T09:28:25.5734Z [I] Evaluating installedCriteria 3.0.0 [GetIsInstalled]
2022-05-19T09:28:26.2431Z [I] 2022-05-19T09:28:25.5765Z [I] Run as uid(0), defaultUid(0), effectiveUid(0), effectiveGid(0) [main]
2022-05-19T09:28:26.2427Z [I] ########## Begin Child's Logs ########## [ShowChildProcessLogs]
2022-05-19T09:28:26.2428Z [I] #  Reading package lists... [ShowChildProcessLogs]
2022-05-19T09:28:26.2428Z [I] #  Building dependency tree... [ShowChildProcessLogs]
2022-05-19T09:28:26.2428Z [I] #  Reading state information... [ShowChildProcessLogs]
2022-05-19T09:28:26.2428Z [I] #  deliveryoptimization-agent is already the newest version (0.6.0). [ShowChildProcessLogs]
2022-05-19T09:28:26.2428Z [I] #  0 upgraded, 0 newly installed, 0 to remove and 26 not upgraded. [ShowChildProcessLogs]
2022-05-19T09:28:26.2428Z [I] ########## End Child's Logs ########## [ShowChildProcessLogs]
 [Install]
2022-05-19T09:28:26.2491Z [I] Apply succeeded [Apply]
2022-05-19T09:28:26.2491Z [I] Action 'Install' complete. Result: 600 (succeeded), 0 (0x0) [ADUC_Workflow_WorkCompletionCallback]
```

**Comment by jw-msft** [comment]
Let us know if you can repro on 1.0.2 patch, but we don't officially support running in docker yet.
