### ISSUE TITLE
Issue with Manifest File Upload on Azure Portal

### ISSUE THREAD

**Issue by marcelo-luna** [Azure/iot-hub-device-update#665]
Since four days ago, I have been encountering an error when attempting to upload manifest files to the Azure Portal. Previously, this process worked well, but now, when I try to upload files from my storage account, I receive the following error message:

> "A problem occurred trying to parse the schema for one or more import manifests. Delete the file or adjust its syntax, and try again."

![Image](https://github.com/user-attachments/assets/2167fd6d-49af-437e-83b8-9a0a981337b0)

I am using the same files that I previously uploaded successfully, and I also downloaded [sample files](https://learn.microsoft.com/en-us/azure/iot-hub-device-update/device-update-ubuntu-agent#import-the-update) from the documentation to confirm that the issue is not with the files themselves.

Additional Information: I noticed this message in Chrome DevTools:

```javascript
[Microsoft_Azure_IotHub]  10:51:10 AM Shared/Log 403 Log: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
RequestId:b0e0da15-901e-0006-32e8-29ae89000000
Time:2024-10-29T09:51:10.8797831Z</Message></Error> 
``` 

![Image](https://github.com/user-attachments/assets/a293fe6e-c96f-418a-b1ba-db9c1f7187f1)

**Comment by Wallemz** [comment]
Same here, we're using the same file we used previously.
![Image](https://github.com/user-attachments/assets/62f4689e-950c-4957-b911-212083f25b96)

**Comment by andrewbrownmsft** [comment]
Can you please try adding the "Storage Blob Data Contributor" role on the storage account? That should resolve the issue.

**Comment by marcelo-luna** [comment]
I added "Storage Blob Data Contributor" on the storage account for "Azure Device Update" but I'm still getting the same error. As I mentioned before it was working well last week until friday and I never had to add this role before.  

![Image](https://github.com/user-attachments/assets/76937273-2064-487b-9ec3-f36ea40434f3)

**Comment by andrewbrownmsft** [comment]
Yes, there was a change that requires this role. Please wait a few hours and check again, as this has been the solution internally and for other customers to address the issue.

Also, can you confirm the steps you are taking to add the role? The screenshot above indicates the role is being added, but not that the role itself is assigned (that would be the last step in the wizard shown in the screenshot). It would be useful to see a screenshot like this one:

![Image](https://github.com/user-attachments/assets/2e9c86f8-1df8-4946-abfa-4b8e14888d7c)

**Comment by andrewbrownmsft** [comment]
Step by step instructions:

1.	In the Azure portal, search for the “Storage accounts” service in the search bar at the top of the page.
2.	Select the “Storage accounts” service.
3.	In the Storage accounts view, locate the Storage account that you’re using with Device Update for IoT Hub. Select that account.
4.	In the selected Storage account, select the “Containers” option under the “Data storage” header.
5.	Locate the container that you’re using with Device Update for IoT Hub. Select that container.
6.	In the Container view, select “Access Control (IAM) from the left-hand navigation menu.
7.	Select “Add” -> “Add role assignment” from the top menu.
8.	In the Role tab, search for the “Storage Blob Data Contributor” role and select it, then click Next.
9.	In the Members tab, keep the default selection of “User, group or service principal”, and select the “Select members” link. In the right-hand flyout menu, search for your user account, select it, and choose the “Select” button. Then select Next.
10.	In the Conditions tab, make no changes and select “Next”.
11.	In the Review + assign tab, select “Review + assign”.
12.	Allow a few minutes for the change to propagate, and then try the Device Update for IoT Hub import experience again from the beginning.

**Comment by marcelo-luna** [comment]
Sorry for the late answer @andrewbrownmsft.

I tested again with the changes that I had made before and worked fine, I think when I tried last week it was not propagated properly as you mentioned. 

The steps that I took were little different from yours, instead add role into Container I added for the entire Storage Account.

Thanks!
